### ISSUE TITLE
Temporary might damage is a cumbersome rule

### ISSUE THREAD

**Issue by n0la** [ehrpg/qstar#15]
## Problem:

If a character receives temporary might damage (e.g. through a disease) he must roll his racial hit die to determine his HP loss. Then, once the might rank is restored, he must roll a hit die again to regain the lost hit points. This might leave him with less or even more HP than before the temporary might damage.

This rule needs to be changed.

## Solution A:

Temporary might damage just reduces you by the average of the hit die (rounded down).

## Solution B:

Use fixed HP values gained upon new might ranks.

**Comment by johannes-z** [comment]
Another proposal:

## Solution C:

Lose a fixed amount of health per lost might rank (e.g. losing 1 might rank reduces the character's HP by 5).
