### ISSUE TITLE
Break-action shotguns are underpowered

### ISSUE THREAD

**Issue by n0la** [ehrpg/qstar#16]
The break action shotguns (TOZ-66 and TOZ-34) are underpowered for their price. They are limited to two shots, take forever to reload, their ammunition is expensive (2 RUB for one shell, compared to 0.3 for one 5.45x39 round), and only cost 2k (or 3k) less than a full powered rifle. Full powered rifles have the added benefit of a higher RoF, making it far easier to hit with a rifle than with a shotgun.

* Perhaps make the TOZ-66 and TOZ-34 cheaper.
* Perhaps make the 12G shell cheaper.
* Or increase damage of 12G Buckshot for close range (leave mid range damage as is).
* Maybe give a bonus for 12G Buckshot when the target is moving. That's what buckshot and birdshot was meant to do: make it easier to hit fast moving targets at a distance (i.e. clay, or flying birds).
* Both TOZ-66 and 34 could have a new fire mode called **double shot** where both barrels are fired at the same time (it's possible IRL as [both barrels have different triggers](https://picturearchive.gunauction.com/129204511/10084349/002_edited-2.jpg_thumbnail1.jpg)), giving it a RoF of 2.
* Perhaps include 12G slug, to allow the shotguns to be used as makeshift rifles (with less accuracy than a real rifle of course).

**Comment by johannes-z** [comment]
Damage has increased vs. targets with no DR in close range. Also, 12G shells were made cheaper.

New ammo types and weapon upgrades will be added for better stats.

Double shot will be added to the listed shotguns too.
